forcingCases = {'dtP',5:5:150,...
				'T0',-2:16,...
				'Tb0_over_T0',[0.4 1]};
paramCases = {'Nyears',4,...
			  'tegg',0,...
			  'u0',0.005:0.001:0.01,...
			  'Ks',1,...
			  'm0',0.08};
filename = '~/datasets/coltrane_runs/global/';

[cases,stats,p1,forcing1] = ...
	coltraneEnsemble('simple-g',forcingCases,paramCases,filename);
save runs_global_stats stats cases p1 forcing1
